apiVersion: v1
kind: PersistentVolume
metadata:
  name: product
  labels:
    app: product
spec:
  storageClassName: nfs-retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.138.37.203
    path: /data/product
