apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: standard
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-076a56ee-fa02-4cbf-aa22-cafa9d264dc9
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: product
    namespace: default
  nfs:
    path: /data/default-product-pvc-076a56ee-fa02-4cbf-aa22-cafa9d264dc9
    server: 10.138.37.203
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-delete
  volumeMode: Filesystem
