apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: standard
  creationTimestamp: "2021-03-20T03:17:52Z"
  finalizers:
  - kubernetes.io/pv-protection
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-20T03:17:52Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:pv.kubernetes.io/provisioned-by: {}
      f:spec:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:claimRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
          f:resourceVersion: {}
          f:uid: {}
        f:nfs:
          .: {}
          f:path: {}
          f:server: {}
        f:persistentVolumeReclaimPolicy: {}
        f:storageClassName: {}
        f:volumeMode: {}
    manager: nfs-client-provisioner
    operation: Update
    time: "2021-03-20T03:17:52Z"
  name: pvc-076a56ee-fa02-4cbf-aa22-cafa9d264dc9
  resourceVersion: "90184"
  selfLink: /api/v1/persistentvolumes/pvc-076a56ee-fa02-4cbf-aa22-cafa9d264dc9
  uid: 8f2e0188-a5e1-4ca5-b6f7-47236e33fb7b
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: product
    namespace: default
    resourceVersion: "90179"
    uid: 076a56ee-fa02-4cbf-aa22-cafa9d264dc9
  nfs:
    path: /data/default-product-pvc-076a56ee-fa02-4cbf-aa22-cafa9d264dc9
    server: 10.138.37.203
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-delete
  volumeMode: Filesystem
status:
  phase: Bound
